version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    hostname: cortito-api
    restart: always
    env_file:
      - .env
    depends_on:
      - account
      - shortener
      - cortito-api

  account:
    build:
      context: .
      dockerfile: ./docker/account/Dockerfile
    hostname: cortito-account
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres-account
      - consul

  shortener:
    build:
      context: .
      dockerfile: ./docker/shortener/Dockerfile
    hostname: cortito-shortener
    restart: always
    env_file:
      - .env
    depends_on:
      - consul
      - postgres-shortener

  nginx:
    image: cortito_nginx:latest
    hostname: nginx
    container_name: api-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - cortito-api

  postgres-account:
    image: postgres:latest
    hostname: postgres-account
    restart: always
    volumes:
      - postgres-account:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${ACCOUNT_DB_NAME:-cortito_account}

  postgres-shortener:
    image: postgres:latest
    hostname: postgres-shortener
    restart: always
    volumes:
      - postgres-shortener:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SHORTENER_DB_NAME:-cortito_shortener}

  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    hostname: consul
    restart: always
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  micro-web:
    image: microhq/micro
    command: web_tmp --namespace=io.coderoso.cortito
    hostname: micro-web_tmp
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - consul

  cortito-api:
    image: microhq/micro
    command: api --handler=http --namespace=io.coderoso.cortito --resolver=micro
    hostname: cortito-api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - consul

volumes:
  postgres-account:
  postgres-shortener:
