version: "3"

services:
  frontend:
    image: coderoso/cortito_frontend
    hostname: frontend
    env_file:
      - .env
    depends_on:
      - cortito-api
    volumes:
      - frontend:/cortito

  api:
    image: coderoso/cortito_api
    hostname: api
    restart: always
    volumes:
      - ./api/config.yml:/cortito/config.yml
      - ./api/config.${APP_ENV:-development}.yml:/cortito/config.${APP_ENV:-development}.yml
    env_file:
      - .env
    depends_on:
      - consul
      - account
      - shortener
      - cortito-api

  account:
    image: coderoso/cortito_account
    hostname: cortito-account
    restart: always
    volumes:
      - ./account/config.yml:/cortito/config.yml
      - ./account/config.${APP_ENV:-development}.yml:/cortito/config.${APP_ENV:-development}.yml
      - ./jwt.pem.key:/cortito/jwt.pem.key
      - ./jwt.pem.key.pub:/cortito/jwt.pem.key.pub
    env_file:
      - .env
    depends_on:
      - postgres-account
      - consul

  shortener:
    image: coderoso/cortito_shortener
    hostname: cortito-shortener
    restart: always
    volumes:
      - ./shortener/config.yml:/cortito/config.yml
      - ./shortener/config.${APP_ENV:-development}.yml:/cortito/config.${APP_ENV:-development}.yml
      - ./jwt.pem.key:/cortito/jwt.pem.key
      - ./jwt.pem.key.pub:/cortito/jwt.pem.key.pub
    env_file:
      - .env
    depends_on:
      - consul
      - postgres-shortener

  web:
    image: coderoso/cortito_web
    hostname: cortito
    restart: always
    volumes:
      - ./web/config.yml:/cortito/config.yml
      - ./web/config.${APP_ENV:-development}.yml:/cortito/config.${APP_ENV:-development}.yml
    env_file:
      - .env
    depends_on:
      - shortener

  nginx:
    image: coderoso/cortito_nginx:latest
    hostname: nginx
    container_name: cortito-nginx
    restart: always
    volumes:
      - frontend:/cortito
    ports:
      - 8000:8000
      - 8443:443
    depends_on:
      - cortito-api

  postgres-account:
    image: postgres:latest
    hostname: postgres-account
    restart: always
    volumes:
      - postgres-account:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${ACCOUNT_DB_NAME:-cortito_account}

  postgres-shortener:
    image: postgres:latest
    hostname: postgres-shortener
    restart: always
    volumes:
      - postgres-shortener:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SHORTENER_DB_NAME:-cortito_shortener}

  redis:
    image: redis:alpine
    hostname: redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - .env

  certbot:
    image: certbot/certbot
    hostname: certbot
    container_name: cortito-certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    hostname: consul
    restart: always
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  micro-web:
    image: microhq/micro
    command: web --namespace=io.coderoso.cortito
    hostname: micro-web
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - consul

  cortito-api:
    image: microhq/micro
    command: api --handler=http --namespace=io.coderoso.cortito --resolver=micro
    hostname: cortito-api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - consul

volumes:
  postgres-account:
  postgres-shortener:
  frontend:
  redis-data:
