export const LINKS_REQUEST = 'LINKS_REQUEST'
export const LINKS_SUCCESS = 'LINKS_SUCCESS'
export const LINKS_FAILURE = 'LINKS_FAILURE'

export const CREATE_LINK_REQUEST = 'CREATE_LINK_REQUEST'
export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS'
export const CREATE_LINK_FAILURE = 'CREATE_LINK_FAILURE'

export const ON_LINK_FIELD_CHANGED = 'ON_LINK_FIELD_CHANGED'

export const HIDE_ALERT = 'HIDE_ALERT'
