// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/shortener/shortener.proto

package shortener

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors.js if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateLinkRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Visits               int32    `protobuf:"varint,4,opt,name=visits,proto3" json:"visits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLinkRequest) Reset()         { *m = CreateLinkRequest{} }
func (m *CreateLinkRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLinkRequest) ProtoMessage()    {}
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shortener_38609bd6dbd030f4, []int{0}
}
func (m *CreateLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLinkRequest.Unmarshal(m, b)
}
func (m *CreateLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLinkRequest.Marshal(b, m, deterministic)
}
func (dst *CreateLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLinkRequest.Merge(dst, src)
}
func (m *CreateLinkRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLinkRequest.Size(m)
}
func (m *CreateLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLinkRequest proto.InternalMessageInfo

func (m *CreateLinkRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateLinkRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateLinkRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *CreateLinkRequest) GetVisits() int32 {
	if m != nil {
		return m.Visits
	}
	return 0
}

type ListLinksRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLinksRequest) Reset()         { *m = ListLinksRequest{} }
func (m *ListLinksRequest) String() string { return proto.CompactTextString(m) }
func (*ListLinksRequest) ProtoMessage()    {}
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shortener_38609bd6dbd030f4, []int{1}
}
func (m *ListLinksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLinksRequest.Unmarshal(m, b)
}
func (m *ListLinksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLinksRequest.Marshal(b, m, deterministic)
}
func (dst *ListLinksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLinksRequest.Merge(dst, src)
}
func (m *ListLinksRequest) XXX_Size() int {
	return xxx_messageInfo_ListLinksRequest.Size(m)
}
func (m *ListLinksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLinksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLinksRequest proto.InternalMessageInfo

func (m *ListLinksRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListLinksResponse struct {
	Links                []*LinkResponse `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListLinksResponse) Reset()         { *m = ListLinksResponse{} }
func (m *ListLinksResponse) String() string { return proto.CompactTextString(m) }
func (*ListLinksResponse) ProtoMessage()    {}
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_shortener_38609bd6dbd030f4, []int{2}
}
func (m *ListLinksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLinksResponse.Unmarshal(m, b)
}
func (m *ListLinksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLinksResponse.Marshal(b, m, deterministic)
}
func (dst *ListLinksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLinksResponse.Merge(dst, src)
}
func (m *ListLinksResponse) XXX_Size() int {
	return xxx_messageInfo_ListLinksResponse.Size(m)
}
func (m *ListLinksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLinksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListLinksResponse proto.InternalMessageInfo

func (m *ListLinksResponse) GetLinks() []*LinkResponse {
	if m != nil {
		return m.Links
	}
	return nil
}

type LinkRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkRequest) Reset()         { *m = LinkRequest{} }
func (m *LinkRequest) String() string { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()    {}
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shortener_38609bd6dbd030f4, []int{3}
}
func (m *LinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkRequest.Unmarshal(m, b)
}
func (m *LinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkRequest.Marshal(b, m, deterministic)
}
func (dst *LinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkRequest.Merge(dst, src)
}
func (m *LinkRequest) XXX_Size() int {
	return xxx_messageInfo_LinkRequest.Size(m)
}
func (m *LinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkRequest proto.InternalMessageInfo

func (m *LinkRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type LinkResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Visits               int32    `protobuf:"varint,5,opt,name=visits,proto3" json:"visits,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastVisit            string   `protobuf:"bytes,8,opt,name=last_visit,json=lastVisit,proto3" json:"last_visit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkResponse) Reset()         { *m = LinkResponse{} }
func (m *LinkResponse) String() string { return proto.CompactTextString(m) }
func (*LinkResponse) ProtoMessage()    {}
func (*LinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_shortener_38609bd6dbd030f4, []int{4}
}
func (m *LinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkResponse.Unmarshal(m, b)
}
func (m *LinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkResponse.Marshal(b, m, deterministic)
}
func (dst *LinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkResponse.Merge(dst, src)
}
func (m *LinkResponse) XXX_Size() int {
	return xxx_messageInfo_LinkResponse.Size(m)
}
func (m *LinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkResponse proto.InternalMessageInfo

func (m *LinkResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LinkResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LinkResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LinkResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *LinkResponse) GetVisits() int32 {
	if m != nil {
		return m.Visits
	}
	return 0
}

func (m *LinkResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *LinkResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *LinkResponse) GetLastVisit() string {
	if m != nil {
		return m.LastVisit
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateLinkRequest)(nil), "shortener.CreateLinkRequest")
	proto.RegisterType((*ListLinksRequest)(nil), "shortener.ListLinksRequest")
	proto.RegisterType((*ListLinksResponse)(nil), "shortener.ListLinksResponse")
	proto.RegisterType((*LinkRequest)(nil), "shortener.LinkRequest")
	proto.RegisterType((*LinkResponse)(nil), "shortener.LinkResponse")
}

func init() {
	proto.RegisterFile("proto/shortener/shortener.proto", fileDescriptor_shortener_38609bd6dbd030f4)
}

var fileDescriptor_shortener_38609bd6dbd030f4 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0x4d, 0xff, 0x50, 0xe8, 0xf0, 0xfb, 0x19, 0x98, 0x03, 0x6c, 0x10, 0x23, 0xf6, 0x44, 0x62,
	0xc4, 0x04, 0x8f, 0x5e, 0x54, 0x12, 0x12, 0x12, 0x4e, 0x3d, 0x78, 0x25, 0xd5, 0x6e, 0xc2, 0x2a,
	0x69, 0xb1, 0xb3, 0xf5, 0x83, 0xf8, 0xd1, 0xfc, 0x44, 0x66, 0x77, 0x81, 0x2e, 0x01, 0x43, 0xbc,
	0xcd, 0xbe, 0x37, 0x7f, 0xde, 0xbc, 0x59, 0xb8, 0x5c, 0x17, 0xb9, 0xcc, 0x6f, 0x69, 0x99, 0x17,
	0x92, 0x67, 0xbc, 0xa8, 0xa2, 0x91, 0x66, 0x30, 0xdc, 0x01, 0xd1, 0x1b, 0xb4, 0x27, 0x05, 0x4f,
	0x24, 0x9f, 0x8b, 0xec, 0x3d, 0xe6, 0x1f, 0x25, 0x27, 0x89, 0x5d, 0xa8, 0x97, 0xc4, 0x8b, 0x85,
	0x48, 0x99, 0x33, 0x70, 0x86, 0xb5, 0x38, 0x50, 0xcf, 0x59, 0x8a, 0x2d, 0xf0, 0xca, 0x62, 0xc5,
	0xdc, 0x81, 0x33, 0x0c, 0x63, 0x15, 0x22, 0x82, 0xbf, 0x4c, 0x68, 0xc9, 0x3c, 0x0d, 0xe9, 0x18,
	0x3b, 0x10, 0x7c, 0x0a, 0x12, 0x92, 0x98, 0x6f, 0xaa, 0xcd, 0x2b, 0xba, 0x86, 0xd6, 0x5c, 0x90,
	0x54, 0x93, 0xe8, 0xd4, 0xa8, 0xe8, 0x09, 0xda, 0x56, 0x32, 0xad, 0xf3, 0x8c, 0x38, 0xde, 0x40,
	0x6d, 0xa5, 0x00, 0xe6, 0x0c, 0xbc, 0x61, 0x73, 0xdc, 0x1d, 0x55, 0x9b, 0x19, 0xfd, 0x26, 0x2f,
	0x36, 0x59, 0xd1, 0x15, 0x34, 0xed, 0xb5, 0xb6, 0x5a, 0x9d, 0x4a, 0x6b, 0xf4, 0xed, 0xc0, 0x3f,
	0xbb, 0x14, 0xcf, 0xc0, 0xdd, 0x69, 0x71, 0x45, 0x6a, 0x0b, 0x74, 0x8f, 0x79, 0xe1, 0x1d, 0x7a,
	0xe1, 0x1f, 0xf5, 0xa2, 0x66, 0x7b, 0x81, 0x17, 0x00, 0xaf, 0xda, 0xf7, 0x74, 0x91, 0x48, 0x16,
	0xe8, 0x8a, 0x70, 0x83, 0x3c, 0x4a, 0x45, 0x97, 0xeb, 0x74, 0x4b, 0xd7, 0x0d, 0xbd, 0x41, 0x0c,
	0xbd, 0x4a, 0x48, 0x2e, 0x74, 0x33, 0xd6, 0x30, 0xb4, 0x42, 0x9e, 0x15, 0x30, 0xfe, 0x72, 0xc1,
	0x57, 0x4b, 0xe1, 0x04, 0xa0, 0xba, 0x2e, 0xf6, 0x2d, 0xbb, 0x0e, 0x8e, 0xde, 0xfb, 0xcd, 0x4c,
	0x9c, 0x42, 0xb8, 0xbb, 0x04, 0x9e, 0xef, 0x65, 0xed, 0x1f, 0xb3, 0xd7, 0x3f, 0x4e, 0x6e, 0xfa,
	0xdc, 0x43, 0x63, 0x2a, 0xb2, 0x54, 0x4b, 0xe9, 0x1c, 0x0c, 0x3b, 0x21, 0xe2, 0x01, 0xfe, 0xcf,
	0x32, 0xe5, 0x0f, 0x71, 0xbd, 0xe3, 0x9f, 0x3b, 0xbc, 0x04, 0xfa, 0xef, 0xdf, 0xfd, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x2a, 0x55, 0x02, 0x3d, 0x1e, 0x03, 0x00, 0x00,
}
